// Dados de exemplo para países (substitua por seus dados reais)
const countriesData = [
    {
        id: 'canada',
        name: 'Canadá',
        flag: 'https://upload.wikimedia.org/wikipedia/commons/d/d9/Flag_of_Canada_%28Pantone%29.svg',
        latitude: 56.1304,
        longitude: -106.3468,
        rating: 92,
        costOfLiving: 70,
        jobOpportunities: 90,
        healthSystem: 85,
        educationQuality: 90,
        safety: 95,
        averageSalary: 4500, // CAD
        currency: 'CAD',
        exchangeRateToBRL: 3.8, // 1 CAD = 3.8 BRL (exemplo)
        languages: ['Inglês', 'Francês'],
        visaRequirements: 'Visto de estudo ou trabalho necessário',
        climate: 'Temperado a Ártico',
        transportation: {
            public: 'Extenso em grandes cidades',
            private: 'Estradas bem mantidas',
            cost: 'Médio',
            commuteTime: '20-40 min'
        },
        rent: {
            studio: 1200, // CAD
            oneBedroom: 1500, // CAD
            threeBedroom: 2500 // CAD
        },
        universities: [
            { name: 'University of Toronto', rank: 1, programs: ['Engenharia', 'Ciência da Computação', 'Negócios'], tuition: { undergraduate: 30000, postgraduate: 20000 }, link: 'https://www.utoronto.ca/' },
            { name: 'University of British Columbia', rank: 2, programs: ['Artes', 'Ciências Ambientais', 'Medicina'], tuition: { undergraduate: 28000, postgraduate: 18000 }, link: 'https://www.ubc.ca/' }
        ],
        scholarships: [
            { name: 'Vanier Canada Graduate Scholarships', value: '50,000 CAD/ano', description: 'Para estudantes de pós-graduação.', link: '#' },
            { name: 'Quebec Merit Scholarships for Foreign Students', value: '10,000 CAD/ano', description: 'Para estudantes no Quebec.', link: '#' }
        ],
        news: [
            { title: 'Canadá anuncia novas regras de imigração para estudantes', date: '2025-06-15', link: '#' },
            { title: 'Mercado de trabalho de tecnologia em alta em Vancouver', date: '2025-06-10', link: '#' }
        ]
    },
    {
        id: 'portugal',
        name: 'Portugal',
        flag: 'https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Portugal.svg',
        latitude: 39.3999,
        longitude: -8.2245,
        rating: 88,
        costOfLiving: 80,
        jobOpportunities: 70,
        healthSystem: 80,
        educationQuality: 85,
        safety: 90,
        averageSalary: 1200, // EUR
        currency: 'EUR',
        exchangeRateToBRL: 5.5, // 1 EUR = 5.5 BRL (exemplo)
        languages: ['Português'],
        visaRequirements: 'Visto de estudo ou trabalho necessário',
        climate: 'Mediterrânico',
        transportation: {
            public: 'Boa rede de transportes',
            private: 'Estradas em bom estado',
            cost: 'Baixo',
            commuteTime: '15-30 min'
        },
        rent: {
            studio: 500, // EUR
            oneBedroom: 700, // EUR
            threeBedroom: 1200 // EUR
        },
        universities: [
            { name: 'Universidade de Lisboa', rank: 1, programs: ['Direito', 'Engenharia', 'Medicina'], tuition: { undergraduate: 3000, postgraduate: 2500 }, link: 'https://www.ulisboa.pt/' },
            { name: 'Universidade do Porto', rank: 2, programs: ['Artes', 'Arquitetura', 'Economia'], tuition: { undergraduate: 2800, postgraduate: 2200 }, link: 'https://www.up.pt/' }
        ],
        scholarships: [
            { name: 'Bolsas de Estudo para Estrangeiros (DGES)', value: 'Variável', description: 'Bolsas anuais do governo português.', link: '#' },
            { name: 'Bolsas Santander Universidades', value: 'Variável', description: 'Bolsas para estudantes ibero-americanos.', link: '#' }
        ],
        news: [
            { title: 'Portugal entre os melhores países para se viver em 2025', date: '2025-05-20', link: '#' },
            { title: 'Crescimento do setor de turismo impulsiona empregos', date: '2025-05-18', link: '#' }
        ]
    },
    {
        id: 'germany',
        name: 'Alemanha',
        flag: 'https://upload.wikimedia.org/wikipedia/commons/b/ba/Flag_of_Germany.svg',
        latitude: 51.1657,
        longitude: 10.4515,
        rating: 90,
        costOfLiving: 65,
        jobOpportunities: 85,
        healthSystem: 90,
        educationQuality: 95,
        safety: 88,
        averageSalary: 3500, // EUR
        currency: 'EUR',
        exchangeRateToBRL: 5.5, // 1 EUR = 5.5 BRL (exemplo)
        languages: ['Alemão'],
        visaRequirements: 'Visto de estudo ou trabalho necessário',
        climate: 'Temperado',
        transportation: {
            public: 'Excelente e pontual',
            private: 'Autobahns de alta qualidade',
            cost: 'Médio a alto',
            commuteTime: '20-45 min'
        },
        rent: {
            studio: 600, // EUR
            oneBedroom: 800, // EUR
            threeBedroom: 1500 // EUR
        },
        universities: [
            { name: 'Technical University of Munich (TUM)', rank: 1, programs: ['Engenharia', 'Ciência da Computação', 'Ciências Naturais'], tuition: { undergraduate: 0, postgraduate: 0 }, link: 'https://www.tum.de/' },
            { name: 'Heidelberg University', rank: 2, programs: ['Medicina', 'Direito', 'Humanidades'], tuition: { undergraduate: 0, postgraduate: 0 }, link: 'https://www.uni-heidelberg.de/en' }
        ],
        scholarships: [
            { name: 'DAAD Scholarships', value: 'Variável', description: 'Para estudantes internacionais.', link: '#' },
            { name: 'Deutschlandstipendium', value: '300 EUR/mês', description: 'Para estudantes talentosos.', link: '#' }
        ],
        news: [
            { title: 'Indústria 4.0 na Alemanha: novas oportunidades de emprego', date: '2025-06-01', link: '#' },
            { title: 'Alemanha investe pesado em energias renováveis', date: '2025-05-25', link: '#' }
        ]
    },
    {
        id: 'australia',
        name: 'Austrália',
        flag: 'https://upload.wikimedia.org/wikipedia/commons/8/88/Flag_of_Australia_%28converted%29.svg',
        latitude: -25.2744,
        longitude: 133.7751,
        rating: 85,
        costOfLiving: 60,
        jobOpportunities: 75,
        healthSystem: 80,
        educationQuality: 88,
        safety: 90,
        averageSalary: 5000, // AUD
        currency: 'AUD',
        exchangeRateToBRL: 3.5, // 1 AUD = 3.5 BRL (exemplo)
        languages: ['Inglês'],
        visaRequirements: 'Visto de estudo ou trabalho necessário',
        climate: 'Variado, de tropical a temperado',
        transportation: {
            public: 'Bom em cidades, menos em áreas rurais',
            private: 'Estradas de boa qualidade',
            cost: 'Alto',
            commuteTime: '30-60 min'
        },
        rent: {
            studio: 1400, // AUD
            oneBedroom: 1800, // AUD
            threeBedroom: 3000 // AUD
        },
        universities: [
            { name: 'University of Melbourne', rank: 1, programs: ['Medicina', 'Direito', 'Engenharia'], tuition: { undergraduate: 35000, postgraduate: 25000 }, link: 'https://unimelb.edu.au/' },
            { name: 'University of Sydney', rank: 2, programs: ['Artes', 'Ciência', 'Negócios'], tuition: { undergraduate: 32000, postgraduate: 23000 }, link: 'https://www.sydney.edu.au/' }
        ],
        scholarships: [
            { name: 'Australia Awards Scholarships', value: 'Cobertura total', description: 'Para estudantes de países em desenvolvimento.', link: '#' },
            { name: 'Destination Australia Program', value: '15,000 AUD/ano', description: 'Para estudos em regiões rurais.', link: '#' }
        ],
        news: [
            { title: 'Boom na demanda por profissionais de saúde na Austrália', date: '2025-06-05', link: '#' },
            { title: 'Novas políticas de imigração para graduados', date: '2025-05-30', link: '#' }
        ]
    }
];

// Estado da aplicação
const appState = {
    isDarkMode: false,
    selectedEducationLevel: 'Ensino Médio',
    selectedCategories: ['Custo de Vida', 'Oportunidades de Trabalho'],
    idealScore: 80,
    searchQuery: '',
    map: null,
    markers: L.featureGroup(),
    currentCountryData: null,
    countriesToCompare: [],
    notifications: []
};

// Traduções
const translations = {
    pt: {
        appTitle: 'Morar no Mundo',
        appSubtitle: 'Salários Reais 2025 • Bolsas por Formação • Contatos por Localização • Dados Atualizados',
        filtersTitle: 'Filtros',
        searchCountry: 'Buscar País',
        searchCountryPlaceholder: 'Digite o nome do país...',
        educationLevel: 'Nível de Educação',
        highSchool: 'Ensino Médio',
        graduation: 'Graduação',
        postGraduation: 'Pós-graduação',
        phd: 'Doutorado',
        interestCategories: 'Categorias de Interesse',
        costOfLiving: 'Custo de Vida',
        jobOpportunities: 'Oportunidades de Trabalho',
        healthSystem: 'Sistema de Saúde',
        education: 'Educação',
        safety: 'Segurança',
        idealScore: 'Pontuação Ideal',
        applyFilters: 'Aplicar Filtros',
        mapTitle: 'Países no Mapa',
        legendHigh: 'Alto',
        legendMedium: 'Médio',
        legendLow: 'Baixo',
        salary: 'Salário Médio',
        rent: 'Aluguel Médio',
        visa: 'Visto',
        languages: 'Idiomas',
        climate: 'Clima',
        transportation: 'Transporte',
        detailsBtn: 'Ver Detalhes',
        compareBtn: 'Comparar',
        countryDetailsTitle: 'Detalhes do País',
        details: 'Detalhes',
        universities: 'Universidades',
        scholarships: 'Bolsas',
        currencyConverterTitle: 'Conversor de Moedas',
        to: 'para',
        compareCountries: 'Comparar Países',
        clearComparison: 'Limpar Comparação',
        login: 'Entrar',
        register: 'Cadastrar',
        emailPlaceholder: 'Email',
        passwordPlaceholder: 'Senha',
        namePlaceholder: 'Nome',
        logout: 'Sair',
        user: 'Usuário',
        notificationsTitle: 'Notificações',
        markAllRead: 'Marcar todas como lidas',
        settings: 'Configurações',
        notificationSettingsTitle: 'Configurações de Notificação',
        allowPushNotifications: 'Permitir notificações push',
        emailNotifications: 'Notificações por Email',
        universityRank: 'Classificação Universitária',
        program: 'Programa',
        tuition: 'Mensalidade',
        link: 'Link',
        value: 'Valor',
        description: 'Descrição',
        news: 'Notícias',
        title: 'Título',
        date: 'Data',
        commuteTime: 'Tempo de Deslocamento',
        publicTransport: 'Transporte Público',
        privateTransport: 'Transporte Privado',
        cost: 'Custo',
        studioRent: 'Aluguel de Estúdio',
        oneBedroomRent: 'Aluguel de Quarto',
        threeBedroomRent: 'Aluguel de Três Quartos',
        averageSalary: 'Salário Médio',
        currency: 'Moeda',
        exchangeRate: 'Taxa de Câmbio',
        generalInformation: 'Informações Gerais',
        socialSecurity: 'Segurança Social',
        entertainment: 'Entretenimento',
        food: 'Alimentação',
        weather: 'Clima',
        culture: 'Cultura',
        userProfile: 'Perfil do Usuário',
        editProfile: 'Editar Perfil',
        changePassword: 'Mudar Senha',
        deleteAccount: 'Excluir Conta',
        saveChanges: 'Salvar Alterações',
        currentPassword: 'Senha Atual',
        newPassword: 'Nova Senha',
        confirmPassword: 'Confirmar Senha',
        deleteAccountWarning: 'Tem certeza que deseja excluir sua conta? Esta ação é irreversível.',
        yes: 'Sim',
        no: 'Não',
        selectCountry: 'Selecione um país para comparar',
        addCountry: 'Adicionar País',
        noCountriesSelected: 'Nenhum país selecionado para comparação.',
        userDashboard: 'Painel do Usuário',
        favouriteCountries: 'Países Favoritos',
        recentViews: 'Visualizações Recentes',
        myReviews: 'Minhas Avaliações',
        reviewPlaceholder: 'Escreva sua avaliação...',
        submitReview: 'Enviar Avaliação',
        reviewScore: 'Pontuação da Avaliação',
        reviewSubmitted: 'Avaliação enviada com sucesso!',
        reviewError: 'Erro ao enviar avaliação.',
        emailSubscription: 'Assinatura de Email',
        subscribe: 'Inscrever-se',
        unsubscribe: 'Cancelar inscrição',
        subscriptionSuccess: 'Assinatura atualizada!',
        subscriptionError: 'Erro ao atualizar assinatura.',
        contactUs: 'Entre em Contato',
        subject: 'Assunto',
        message: 'Mensagem',
        sendMessage: 'Enviar Mensagem',
        messageSent: 'Mensagem enviada com sucesso!',
        messageError: 'Erro ao enviar mensagem.',
        privacyPolicy: 'Política de Privacidade',
        termsOfService: 'Termos de Serviço',
        faq: 'FAQ',
        aboutUs: 'Sobre Nós',
        contactInfo: 'Informações de Contato',
        address: 'Endereço',
        phone: 'Telefone',
        email: 'Email',
        followUs: 'Siga-nos',
        allRightsReserved: 'Todos os direitos reservados.',
        developedBy: 'Desenvolvido por',
        // Novos campos para detalhes adicionais
        internetQuality: 'Qualidade da Internet',
        publicSafety: 'Segurança Pública',
        politicalStability: 'Estabilidade Política',
        environmentalQuality: 'Qualidade Ambiental',
        culturalDiversity: 'Diversidade Cultural',
        costOfEducation: 'Custo da Educação',
        healthcareAccess: 'Acesso à Saúde',
        transportationEfficiency: 'Eficiência do Transporte',
        jobMarketGrowth: 'Crescimento do Mercado de Trabalho',
        entrepreneurshipOpportunities: 'Oportunidades de Empreendedorismo',
        taxRates: 'Taxas de Imposto',
        propertyPrices: 'Preços de Propriedades',
        tourismOpportunities: 'Oportunidades de Turismo',
        recreationalActivities: 'Atividades Recreativas',
        nightlife: 'Vida Noturna',
        cuisine: 'Culinária',
        sports: 'Esportes',
        // Adicionado para o seletor de idioma
        selectYourLanguage: 'Selecione seu idioma'
    },
    en: {
        appTitle: 'Live in the World',
        appSubtitle: 'Real Salaries 2025 • Scholarships by Education • Contacts by Location • Updated Data',
        filtersTitle: 'Filters',
        searchCountry: 'Search Country',
        searchCountryPlaceholder: 'Enter country name...',
        educationLevel: 'Education Level',
        highSchool: 'High School',
        graduation: 'Graduation',
        postGraduation: 'Post-graduation',
        phd: 'PhD',
        interestCategories: 'Interest Categories',
        costOfLiving: 'Cost of Living',
        jobOpportunities: 'Job Opportunities',
        healthSystem: 'Health System',
        education: 'Education',
        safety: 'Safety',
        idealScore: 'Ideal Score',
        applyFilters: 'Apply Filters',
        mapTitle: 'Countries on the Map',
        legendHigh: 'High',
        legendMedium: 'Medium',
        legendLow: 'Low',
        salary: 'Average Salary',
        rent: 'Average Rent',
        visa: 'Visa',
        languages: 'Languages',
        climate: 'Climate',
        transportation: 'Transportation',
        detailsBtn: 'View Details',
        compareBtn: 'Compare',
        countryDetailsTitle: 'Country Details',
        details: 'Details',
        universities: 'Universities',
        scholarships: 'Scholarships',
        currencyConverterTitle: 'Currency Converter',
        to: 'to',
        compareCountries: 'Compare Countries',
        clearComparison: 'Clear Comparison',
        login: 'Login',
        register: 'Register',
        emailPlaceholder: 'Email',
        passwordPlaceholder: 'Password',
        namePlaceholder: 'Name',
        logout: 'Logout',
        user: 'User',
        notificationsTitle: 'Notifications',
        markAllRead: 'Mark all as read',
        settings: 'Settings',
        notificationSettingsTitle: 'Notification Settings',
        allowPushNotifications: 'Allow Push Notifications',
        emailNotifications: 'Email Notifications',
        universityRank: 'University Rank',
        program: 'Program',
        tuition: 'Tuition',
        link: 'Link',
        value: 'Value',
        description: 'Description',
        news: 'News',
        title: 'Title',
        date: 'Date',
        commuteTime: 'Commute Time',
        publicTransport: 'Public Transport',
        privateTransport: 'Private Transport',
        cost: 'Cost',
        studioRent: 'Studio Rent',
        oneBedroomRent: 'One Bedroom Rent',
        threeBedroomRent: 'Three Bedroom Rent',
        averageSalary: 'Average Salary',
        currency: 'Currency',
        exchangeRate: 'Exchange Rate',
        generalInformation: 'General Information',
        socialSecurity: 'Social Security',
        entertainment: 'Entertainment',
        food: 'Food',
        weather: 'Weather',
        culture: 'Culture',
        userProfile: 'User Profile',
        editProfile: 'Edit Profile',
        changePassword: 'Change Password',
        deleteAccount: 'Delete Account',
        saveChanges: 'Save Changes',
        currentPassword: 'Current Password',
        newPassword: 'New Password',
        confirmPassword: 'Confirm Password',
        deleteAccountWarning: 'Are you sure you want to delete your account? This action is irreversible.',
        yes: 'Yes',
        no: 'No',
        selectCountry: 'Select a country to compare',
        addCountry: 'Add Country',
        noCountriesSelected: 'No countries selected for comparison.',
        userDashboard: 'User Dashboard',
        favouriteCountries: 'Favourite Countries',
        recentViews: 'Recent Views',
        myReviews: 'My Reviews',
        reviewPlaceholder: 'Write your review...',
        submitReview: 'Submit Review',
        reviewScore: 'Review Score',
        reviewSubmitted: 'Review submitted successfully!',
        reviewError: 'Error submitting review.',
        emailSubscription: 'Email Subscription',
        subscribe: 'Subscribe',
        unsubscribe: 'Unsubscribe',
        subscriptionSuccess: 'Subscription updated!',
        subscriptionError: 'Error updating subscription.',
        contactUs: 'Contact Us',
        subject: 'Subject',
        message: 'Message',
        sendMessage: 'Send Message',
        messageSent: 'Message sent successfully!',
        messageError: 'Error sending message.',
        privacyPolicy: 'Privacy Policy',
        termsOfService: 'Terms of Service',
        faq: 'FAQ',
        aboutUs: 'About Us',
        contactInfo: 'Contact Info',
        address: 'Address',
        phone: 'Phone',
        email: 'Email',
        followUs: 'Follow Us',
        allRightsReserved: 'All rights reserved.',
        developedBy: 'Developed by',
        // Novos campos para detalhes adicionais
        internetQuality: 'Internet Quality',
        publicSafety: 'Public Safety',
        politicalStability: 'Political Stability',
        environmentalQuality: 'Environmental Quality',
        culturalDiversity: 'Cultural Diversity',
        costOfEducation: 'Cost of Education',
        healthcareAccess: 'Healthcare Access',
        transportationEfficiency: 'Transportation Efficiency',
        jobMarketGrowth: 'Job Market Growth',
        entrepreneurshipOpportunities: 'Entrepreneurship Opportunities',
        taxRates: 'Tax Rates',
        propertyPrices: 'Property Prices',
        tourismOpportunities: 'Tourism Opportunities',
        recreationalActivities: 'Recreational Activities',
        nightlife: 'Nightlife',
        cuisine: 'Cuisine',
        sports: 'Sports',
        // Adicionado para o seletor de idioma
        selectYourLanguage: 'Select your language'
    },
    es: {
        appTitle: 'Vivir en el Mundo',
        appSubtitle: 'Salarios Reales 2025 • Becas por Formación • Contactos por Ubicación • Datos Actualizados',
        filtersTitle: 'Filtros',
        searchCountry: 'Buscar País',
        searchCountryPlaceholder: 'Ingrese el nombre del país...',
        educationLevel: 'Nivel Educativo',
        highSchool: 'Bachillerato',
        graduation: 'Grado',
        postGraduation: 'Posgrado',
        phd: 'Doctorado',
        interestCategories: 'Categorías de Interés',
        costOfLiving: 'Costo de Vida',
        jobOpportunities: 'Oportunidades de Empleo',
        healthSystem: 'Sistema de Salud',
        education: 'Educación',
        safety: 'Seguridad',
        idealScore: 'Puntuación Ideal',